name: topup-credit-ticket
# This workflow is used to run the paymenter topup credit script
# on a schedule or manually.

on:
  # schedule:
  #   - cron: "0 23 * * *" # 06:00 WIB
  #   - cron: "0 3 * * *" # 10:00 WIB
  #   - cron: "0 7 * * *" # 14:00 WIB
  #   - cron: "0 11 * * *" # 18:00 WIB
  #   - cron: "0 15 * * *" # 22:00 WIB
  workflow_dispatch: # manual trigger support
    inputs:
      ENABLE_CREATE_TICKET:
        description: "Enable create ticket?"
        required: false
        default: false
        type: boolean

jobs:
  paymenter-topup-credit-ticket:
    name: paymenter-topup-credit
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - name: Run topup credit ticket script
        run: bun run topup
        env:
          ENABLE_CREATE_TICKET: ${{ inputs.ENABLE_CREATE_TICKET || vars.ENABLE_CREATE_TICKET }}
          BASE_URL: ${{ vars.BASE_URL }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          COOKIE: ${{ secrets.COOKIE }}
